version: "3.8"
services:
  broker:
    build:
      context: ./mqtt-broker
    image: iotcontainerregistry007eu.azurecr.io/broker:latest
    stdin_open: true
    tty: true
    ports:
      - "1883:1883"
      - "8883:8883"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.50"
  mysql:
    build:
      context: ./database
    image: iotcontainerregistry007eu.azurecr.io/mysql:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: foobar
      MYSQL_DATABASE: buildingiot
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "0.50"
  backend:
    build:
      context: ./backend
    image: iotcontainerregistry007eu.azurecr.io/backend:latest
    restart: on-failure
    ports:
      - "5000:5000"
    links:
      - broker
    depends_on:
      - "mysql"
    deploy:
      resources:
        limits:
          cpus: "1.00"
